import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Main from "../components/Main";
import { ArrowCircleDownIcon } from "@heroicons/react/outline";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="bg-[#afb2d1]">
      <Head>
        <title>Sadats Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Main />
      <div className="flex justify-center items-center pb-5">
        <ArrowCircleDownIcon width={30} height={30} />
      </div>
      <Projects />
      <Contact />
      <Footer />
    </div>
  );
}
